# базовые настройки
title: "think wait fast"
description: don't panic
url: "https://actxact.github.io"
baseurl: ""

# красивые ссылки на статьи (без .html)
permalink: /:year/:month/:day/:title/

# обрабатываем Markdown
markdown: kramdown
